Shader "Valtiel/Planet/Surface"
{
    // URP-compatible planet surface shader. Lit by the scene's directional
    // light (with shadows), additional lights, ambient SH, and fog — like
    // URP/Lit — but with optional cubemap inputs sampled by object-space
    // normal so the texture has no UV seams and no pole pinch.
    //
    // The lighting is computed manually (Lambert + N·H specular + SH ambient
    // + additional lights) rather than going through UniversalFragmentPBR.
    // That keeps the shader robust to URP version differences and avoids
    // the SRP batcher / screen-space-shadow interactions that previously
    // killed the main light contribution on this material.
    //
    // Cubemap inputs (generated by the Planet Generator):
    //   _BaseCube   — surface albedo (RGB), sampled by normalOS when enabled
    //   _NormalCube — object-space normal in RGB, rotated to world space and
    //                 used as the shading normal (silhouette stays smooth)
    //   _CloudCube  — cloud density in alpha; darkens the direct light along
    //                 the sun-shifted surface direction (parallax shadow)
    Properties
    {
        [Header(Surface)]
        _BaseMap   ("Base Map (2D)",   2D)   = "white" {}
        _BaseCube  ("Base Cubemap",    Cube) = "" {}
        [Toggle(_USE_BASE_CUBE)]   _UseBaseCube   ("Use Base Cubemap",   Float) = 0
        _BaseColor ("Base Color",      Color) = (1,1,1,1)

        [Header(Shading)]
        _Smoothness    ("Smoothness",    Range(0,1))   = 0.2
        _SpecularPower ("Specular Power", Range(1,256)) = 32
        _AmbientFloor  ("Ambient Floor", Range(0,0.3)) = 0.02

        [Header(Normal Cubemap)]
        _NormalCube ("Normal Cubemap", Cube) = "" {}
        [Toggle(_USE_NORMAL_CUBE)] _UseNormalCube ("Use Normal Cubemap", Float) = 0
        _NormalStrength ("Normal Strength", Range(0,2)) = 1.0

        [Header(Detail Normal (tileable))]
        [Normal] _DetailNormalMap ("Detail Normal Map", 2D) = "bump" {}
        [Toggle(_USE_DETAIL_NORMAL)] _UseDetailNormal ("Use Detail Normal", Float) = 0
        _DetailNormalStrength ("Detail Normal Strength", Range(0,3)) = 1.0
        _DetailTiling         ("Detail Tiling",          Range(0,3)) = 1.0
        _DetailOffsetU        ("Detail Offset U",        Float)      = 0.0
        _DetailOffsetV        ("Detail Offset V",        Float)      = 0.0
        _DetailBlendSharpness ("Detail Triplanar Sharpness", Range(1,16)) = 4.0

        [Header(Cloud Shadow)]
        _CloudCube ("Cloud Cubemap", Cube) = "" {}
        [Toggle(_USE_CLOUD_CUBE)] _UseCloudCube ("Use Cloud Shadow", Float) = 0
        _CloudShadowStrength ("Cloud Shadow Strength", Range(0,1)) = 0.6
        _CloudParallax       ("Cloud Parallax",        Range(0,0.2)) = 0.02

        [Header(Emission)]
        [HDR] _EmissionColor ("Emission Color", Color) = (0,0,0,1)
    }

    SubShader
    {
        Tags
        {
            "RenderType"     = "Opaque"
            "Queue"          = "Geometry"
            "RenderPipeline" = "UniversalPipeline"
            "IgnoreProjector" = "True"
        }
        LOD 200

        Pass
        {
            Name "ForwardLit"
            Tags { "LightMode" = "UniversalForward" }

            HLSLPROGRAM
            #pragma target 3.0

            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN
            #pragma multi_compile_fragment _ _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS
            #pragma multi_compile_fragment _ _ADDITIONAL_LIGHT_SHADOWS
            #pragma multi_compile_fragment _ _SHADOWS_SOFT
            #pragma multi_compile_fog
            #pragma multi_compile_instancing

            #pragma shader_feature_local _USE_BASE_CUBE
            #pragma shader_feature_local _USE_NORMAL_CUBE
            #pragma shader_feature_local _USE_DETAIL_NORMAL
            #pragma shader_feature_local _USE_CLOUD_CUBE

            #pragma vertex   PlanetVert
            #pragma fragment PlanetFrag

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"

            CBUFFER_START(UnityPerMaterial)
                float4 _BaseMap_ST;
                float4 _BaseColor;
                float  _Smoothness;
                float  _SpecularPower;
                float  _AmbientFloor;
                float  _NormalStrength;
                float  _DetailNormalStrength;
                float  _DetailTiling;
                float  _DetailOffsetU;
                float  _DetailOffsetV;
                float  _DetailBlendSharpness;
                float  _CloudShadowStrength;
                float  _CloudParallax;
                float4 _EmissionColor;
                float4 _DetailNormalMap_ST;
            CBUFFER_END

            TEXTURE2D(_BaseMap);          SAMPLER(sampler_BaseMap);
            TEXTURECUBE(_BaseCube);       SAMPLER(sampler_BaseCube);
            TEXTURECUBE(_NormalCube);     SAMPLER(sampler_NormalCube);
            TEXTURECUBE(_CloudCube);      SAMPLER(sampler_CloudCube);
            TEXTURE2D(_DetailNormalMap);  SAMPLER(sampler_DetailNormalMap);

            struct Attributes
            {
                float4 positionOS : POSITION;
                float3 normalOS   : NORMAL;
                float2 uv         : TEXCOORD0;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            struct Varyings
            {
                float4 positionCS : SV_POSITION;
                float2 uv         : TEXCOORD0;
                float3 positionWS : TEXCOORD1;
                float3 normalWS   : TEXCOORD2;
                float3 normalOS   : TEXCOORD3;
                float4 shadowCoord: TEXCOORD4;
                float  fogFactor  : TEXCOORD5;
                UNITY_VERTEX_INPUT_INSTANCE_ID
                UNITY_VERTEX_OUTPUT_STEREO
            };

            Varyings PlanetVert(Attributes input)
            {
                Varyings output = (Varyings)0;
                UNITY_SETUP_INSTANCE_ID(input);
                UNITY_TRANSFER_INSTANCE_ID(input, output);
                UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(output);

                VertexPositionInputs posIn = GetVertexPositionInputs(input.positionOS.xyz);
                VertexNormalInputs   nIn   = GetVertexNormalInputs(input.normalOS);

                output.positionCS = posIn.positionCS;
                output.positionWS = posIn.positionWS;
                output.normalWS   = nIn.normalWS;
                output.normalOS   = input.normalOS;
                output.uv         = TRANSFORM_TEX(input.uv, _BaseMap);
                output.shadowCoord = GetShadowCoord(posIn);
                output.fogFactor  = ComputeFogFactor(posIn.positionCS.z);
                return output;
            }

            // Standard Blinn-Phong specular term, driven by smoothness. Kept
            // optional via _Smoothness — set to 0 for a fully matte planet.
            half3 PlanetSpecular(float3 normalWS, float3 viewWS, float3 lightDirWS, half3 lightColor)
            {
                float3 h = normalize(lightDirWS + viewWS);
                float ndh = saturate(dot(normalWS, h));
                float spec = pow(ndh, _SpecularPower) * _Smoothness;
                return lightColor * spec;
            }

            half4 PlanetFrag(Varyings input) : SV_Target
            {
                UNITY_SETUP_INSTANCE_ID(input);
                UNITY_SETUP_STEREO_EYE_INDEX_POST_VERTEX(input);

                float3 normalOS = normalize(input.normalOS);

                // Albedo: cubemap by direction, or 2D fallback.
                #if defined(_USE_BASE_CUBE)
                    half3 albedo = SAMPLE_TEXTURECUBE(_BaseCube, sampler_BaseCube, normalOS).rgb * _BaseColor.rgb;
                #else
                    half3 albedo = SAMPLE_TEXTURE2D(_BaseMap, sampler_BaseMap, input.uv).rgb * _BaseColor.rgb;
                #endif

                // Shading normal: start from the geometric outward (normalOS),
                // optionally perturb by the height-derived cubemap normal
                // (low-frequency macro relief), then optionally add a
                // tileable detail normal via triplanar (high-frequency micro
                // bumps). Both perturbations stack in object space; the final
                // normal is rotated into world space via the model matrix
                // (uniform-scale safe — no inverse-transpose needed).
                float3 nObj = normalOS;

                #if defined(_USE_NORMAL_CUBE)
                    float3 nCube = SAMPLE_TEXTURECUBE(_NormalCube, sampler_NormalCube, normalOS).xyz * 2.0 - 1.0;
                    nObj = normalize(lerp(normalOS, normalize(nCube), saturate(_NormalStrength)));
                #endif

                #if defined(_USE_DETAIL_NORMAL)
                    // Triplanar normal sampling with "whiteout" blending — the
                    // standard technique for combining 3 axis-aligned normal
                    // map samples on an arbitrary surface direction (Ben
                    // Golus / Stephen Hill). On a sphere, the geometric
                    // outward direction IS normalOS, so we use that as the
                    // blending normal.
                    float2 off = float2(_DetailOffsetU, _DetailOffsetV);
                    float2 uvX = normalOS.yz * _DetailTiling + off;
                    float2 uvY = normalOS.xz * _DetailTiling + off;
                    float2 uvZ = normalOS.xy * _DetailTiling + off;

                    float3 tnX = UnpackNormalScale(SAMPLE_TEXTURE2D(_DetailNormalMap, sampler_DetailNormalMap, uvX), _DetailNormalStrength);
                    float3 tnY = UnpackNormalScale(SAMPLE_TEXTURE2D(_DetailNormalMap, sampler_DetailNormalMap, uvY), _DetailNormalStrength);
                    float3 tnZ = UnpackNormalScale(SAMPLE_TEXTURE2D(_DetailNormalMap, sampler_DetailNormalMap, uvZ), _DetailNormalStrength);

                    float3 absN = abs(normalOS);
                    float3 wT = pow(absN, _DetailBlendSharpness);
                    wT /= max(wT.x + wT.y + wT.z, 1e-4);

                    // Whiteout blend: add tangent-space XY onto the surface
                    // normal, keep tangent Z aligned with the projection axis.
                    tnX = float3(tnX.xy + normalOS.zy, abs(tnX.z) * normalOS.x);
                    tnY = float3(tnY.xy + normalOS.xz, abs(tnY.z) * normalOS.y);
                    tnZ = float3(tnZ.xy + normalOS.xy, abs(tnZ.z) * normalOS.z);

                    float3 detailOS = normalize(tnX.zyx * wT.x + tnY.xzy * wT.y + tnZ.xyz * wT.z);

                    // Stack the detail perturbation on top of nObj: take the
                    // detail's deviation from the geometric outward and add
                    // it to nObj. This preserves the cubemap's macro relief
                    // and adds the tileable micro relief.
                    nObj = normalize(nObj + (detailOS - normalOS));
                #endif

                float3 normalWS = normalize(mul((float3x3)UNITY_MATRIX_M, nObj));

                float3 viewWS = SafeNormalize(GetCameraPositionWS() - input.positionWS);

                // --- Main directional light (with shadows) -------------------
                Light mainLight = GetMainLight(input.shadowCoord, input.positionWS, half4(1,1,1,1));
                float ndl = saturate(dot(normalWS, mainLight.direction));
                half3 mainColor  = mainLight.color * mainLight.distanceAttenuation * mainLight.shadowAttenuation;
                half3 mainDirect = albedo * mainColor * ndl;
                half3 mainSpec   = PlanetSpecular(normalWS, viewWS, mainLight.direction, mainColor) * ndl;

                // Cloud parallax shadow on the main light only — shift the
                // sample direction toward the sun by cloudParallax×altitude.
                #if defined(_USE_CLOUD_CUBE)
                    float3 toLightOS  = normalize(mul((float3x3)UNITY_MATRIX_I_M, mainLight.direction));
                    float3 cloudDir   = normalize(normalOS + toLightOS * _CloudParallax);
                    half   cloudDens  = SAMPLE_TEXTURECUBE(_CloudCube, sampler_CloudCube, cloudDir).a;
                    half   shadowFrac = saturate(cloudDens * _CloudShadowStrength);
                    mainDirect *= (1.0 - shadowFrac);
                    mainSpec   *= (1.0 - shadowFrac);
                #endif

                // --- Additional lights (point/spot) --------------------------
                half3 addDirect = half3(0,0,0);
                #if defined(_ADDITIONAL_LIGHTS) || defined(_ADDITIONAL_LIGHTS_VERTEX)
                uint addCount = GetAdditionalLightsCount();
                for (uint i = 0u; i < addCount; ++i)
                {
                    Light l = GetAdditionalLight(i, input.positionWS);
                    half3 atten = l.color * l.distanceAttenuation * l.shadowAttenuation;
                    float nl = saturate(dot(normalWS, l.direction));
                    addDirect += albedo * atten * nl;
                }
                #endif

                // --- Ambient (SH probe) --------------------------------------
                // SampleSH returns the L0+L1+L2 evaluation of the scene's
                // ambient probe — this is what Lighting → Environment →
                // Ambient feeds into. _AmbientFloor adds an optional manual
                // boost so the night side doesn't go to pitch black even with
                // a black ambient.
                half3 sh      = max(half3(0,0,0), SampleSH(normalWS));
                half3 ambient = albedo * (sh + _AmbientFloor);

                half3 color = mainDirect + mainSpec + addDirect + ambient + _EmissionColor.rgb;

                color = MixFog(color, input.fogFactor);
                return half4(color, 1.0);
            }
            ENDHLSL
        }

        // Minimal shadow caster pass so the planet writes to the URP shadow
        // map (other receivers see correct shadows from it). Pulls in URP's
        // standard caster — works because we don't do alpha clipping.
        Pass
        {
            Name "ShadowCaster"
            Tags { "LightMode" = "ShadowCaster" }

            ZWrite On
            ZTest LEqual
            ColorMask 0
            Cull Back

            HLSLPROGRAM
            #pragma target 2.0
            #pragma multi_compile_instancing
            #pragma vertex   ShadowVert
            #pragma fragment ShadowFrag

            #include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Shadows.hlsl"

            float3 _LightDirection;
            float3 _LightPosition;

            struct ShadowAttribs
            {
                float4 positionOS : POSITION;
                float3 normalOS   : NORMAL;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            struct ShadowVaryings
            {
                float4 positionCS : SV_POSITION;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            float4 GetShadowPositionHClip(float3 positionWS, float3 normalWS)
            {
                #if _CASTING_PUNCTUAL_LIGHT_SHADOW
                    float3 lightDirectionWS = normalize(_LightPosition - positionWS);
                #else
                    float3 lightDirectionWS = _LightDirection;
                #endif
                float4 positionCS = TransformWorldToHClip(
                    ApplyShadowBias(positionWS, normalWS, lightDirectionWS));
                #if UNITY_REVERSED_Z
                    positionCS.z = min(positionCS.z, UNITY_NEAR_CLIP_VALUE);
                #else
                    positionCS.z = max(positionCS.z, UNITY_NEAR_CLIP_VALUE);
                #endif
                return positionCS;
            }

            ShadowVaryings ShadowVert(ShadowAttribs input)
            {
                ShadowVaryings o;
                UNITY_SETUP_INSTANCE_ID(input);
                float3 positionWS = TransformObjectToWorld(input.positionOS.xyz);
                float3 normalWS   = TransformObjectToWorldNormal(input.normalOS);
                o.positionCS = GetShadowPositionHClip(positionWS, normalWS);
                return o;
            }

            half4 ShadowFrag(ShadowVaryings i) : SV_Target { return 0; }
            ENDHLSL
        }

        // Depth-only pass (DepthPrepass + DepthOfField + SSAO depend on it).
        Pass
        {
            Name "DepthOnly"
            Tags { "LightMode" = "DepthOnly" }

            ZWrite On
            ColorMask 0
            Cull Back

            HLSLPROGRAM
            #pragma target 2.0
            #pragma multi_compile_instancing
            #pragma vertex   DepthVert
            #pragma fragment DepthFrag

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

            struct DepthA { float4 positionOS : POSITION; UNITY_VERTEX_INPUT_INSTANCE_ID };
            struct DepthV { float4 positionCS : SV_POSITION; UNITY_VERTEX_INPUT_INSTANCE_ID };

            DepthV DepthVert(DepthA i)
            {
                DepthV o;
                UNITY_SETUP_INSTANCE_ID(i);
                o.positionCS = TransformObjectToHClip(i.positionOS.xyz);
                return o;
            }

            half4 DepthFrag(DepthV i) : SV_Target { return 0; }
            ENDHLSL
        }
    }

    FallBack "Universal Render Pipeline/Unlit"
}
